<?php

namespace Rigo\Types;
    
use WPAS\Types\BasePostType;

class Member extends BasePostType{
    
    function initialize(){
        add_action('acf/init', array($this, 'add_member_fields'));
    }

    function add_member_fields() {
    //     acf_add_local_field_group(array(
    //     	'key' => 'member_profile',
    //     	'title' => 'Member Profile',
    //     	'fields' => array(
    //     		array(
    //     			'key' => 'user_name',
    //     			'label' => 'User Name',
    //     			'name' => 'user_name',
    //     			'type' => 'text',
    //     			'instructions' => '',
    //     			'required' => 0,
    //     			'conditional_logic' => 0,
    //     			'wrapper' => array(
    //     				'width' => '',
    //     				'class' => '',
    //     				'id' => '',
    //     			),
    //     			'default_value' => '',
    //     			'placeholder' => '',
    //     			'prepend' => '',
    //     			'append' => '',
    //     			'maxlength' => '',
    //     		),
    //     		array(
    //     			'key' => 'first_name',
    //     			'label' => 'First Name',
    //     			'name' => 'first_name',
    //     			'type' => 'text',
    //     			'instructions' => '',
    //     			'required' => 0,
    //     			'conditional_logic' => 0,
    //     			'wrapper' => array(
    //     				'width' => '',
    //     				'class' => '',
    //     				'id' => '',
    //     			),
    //     			'default_value' => '',
    //     			'placeholder' => '',
    //     			'prepend' => '',
    //     			'append' => '',
    //     			'maxlength' => '',
    //     		),
    //     		array(
    //     			'key' => 'last_name',
    //     			'label' => 'Last Name',
    //     			'name' => 'last_name',
    //     			'type' => 'text',
    //     			'instructions' => '',
    //     			'required' => 0,
    //     			'conditional_logic' => 0,
    //     			'wrapper' => array(
    //     				'width' => '',
    //     				'class' => '',
    //     				'id' => '',
    //     			),
    //     			'default_value' => '',
    //     			'placeholder' => '',
    //     			'prepend' => '',
    //     			'append' => '',
    //     			'maxlength' => '',
    //     		),
    //     		array(
    //     			'key' => 'age',
    //     			'label' => 'Age',
    //     			'name' => 'age',
    //     			'type' => 'text',
    //     			'instructions' => '',
    //     			'required' => 0,
    //     			'conditional_logic' => 0,
    //     			'wrapper' => array(
    //     				'width' => '',
    //     				'class' => '',
    //     				'id' => '',
    //     			),
    //     			'default_value' => '',
    //     			'placeholder' => '',
    //     			'prepend' => '',
    //     			'append' => '',
    //     			'maxlength' => '',
    //     		),
    //     		array(
    //     			'key' => 'gender',
    //     			'label' => 'Gender',
    //     			'name' => 'gender',
    //     			'type' => 'select',
    //     			'instructions' => '',
    //     			'required' => 0,
    //     			'conditional_logic' => 0,
    //     			'wrapper' => array(
    //     				'width' => '',
    //     				'class' => '',
    //     				'id' => '',
    //     			),
    //     			'choices' => array(
    //     				'Male' => 'Male',
    //     				'Female' => 'Female',
    //     			),
    //     			'default_value' => array(
    //     			),
    //     			'allow_null' => 0,
    //     			'multiple' => 0,
    //     			'ui' => 0,
    //     			'return_format' => 'value',
    //     			'ajax' => 0,
    //     			'placeholder' => '',
    //     		),
    //     		array(
    //     			'key' => 'height',
    //     			'label' => 'Height',
    //     			'name' => 'height',
    //     			'type' => 'text',
    //     			'instructions' => 'in cm.',
    //     			'required' => 0,
    //     			'conditional_logic' => 0,
    //     			'wrapper' => array(
    //     				'width' => '',
    //     				'class' => '',
    //     				'id' => '',
    //     			),
    //     			'default_value' => '',
    //     			'placeholder' => '',
    //     			'prepend' => '',
    //     			'append' => '',
    //     			'maxlength' => '',
    //     		),
    //     		array(
    //     			'key' => 'weight',
    //     			'label' => 'Weight',
    //     			'name' => 'weight',
    //     			'type' => 'text',
    //     			'instructions' => 'in lbs.',
    //     			'required' => 0,
    //     			'conditional_logic' => 0,
    //     			'wrapper' => array(
    //     				'width' => '',
    //     				'class' => '',
    //     				'id' => '',
    //     			),
    //     			'default_value' => '',
    //     			'placeholder' => '',
    //     			'prepend' => '',
    //     			'append' => '',
    //     			'maxlength' => '',
    //     		),
    //     		array(
    //     			'key' => 'current_weight',
    //     			'label' => 'Current Weight',
    //     			'name' => 'current_weight',
    //     			'type' => 'text',
    //     			'instructions' => 'in lbs.',
    //     			'required' => 0,
    //     			'conditional_logic' => 0,
    //     			'wrapper' => array(
    //     				'width' => '',
    //     				'class' => '',
    //     				'id' => '',
    //     			),
    //     			'default_value' => '',
    //     			'placeholder' => '',
    //     			'prepend' => '',
    //     			'append' => '',
    //     			'maxlength' => '',
    //     		),
    //     		array(
    //     			'key' => 'goal_weight',
    //     			'label' => 'Goal Weight',
    //     			'name' => 'goal_weight',
    //     			'type' => 'text',
    //     			'instructions' => '',
    //     			'required' => 0,
    //     			'conditional_logic' => 0,
    //     			'wrapper' => array(
    //     				'width' => '',
    //     				'class' => '',
    //     				'id' => '',
    //     			),
    //     			'default_value' => '',
    //     			'placeholder' => '',
    //     			'prepend' => '',
    //     			'append' => '',
    //     			'maxlength' => '',
    //     		),
    //     		array(
    //     			'key' => 'goal_overall',
    //     			'label' => 'Goal Overall',
    //     			'name' => 'goal_overall',
    //     			'type' => 'text',
    //     			'instructions' => '',
    //     			'required' => 0,
    //     			'conditional_logic' => 0,
    //     			'wrapper' => array(
    //     				'width' => '',
    //     				'class' => '',
    //     				'id' => '',
    //     			),
    //     			'default_value' => '',
    //     			'placeholder' => '',
    //     			'prepend' => '',
    //     			'append' => '',
    //     			'maxlength' => '',
    //     		),
    //     		array(
    //     			'key' => 'location',
    //     			'label' => 'Location',
    //     			'name' => 'location',
    //     			'type' => 'text',
    //     			'instructions' => '',
    //     			'required' => 0,
    //     			'conditional_logic' => 0,
    //     			'wrapper' => array(
    //     				'width' => '',
    //     				'class' => '',
    //     				'id' => '',
    //     			),
    //     			'default_value' => '',
    //     			'placeholder' => '',
    //     			'prepend' => '',
    //     			'append' => '',
    //     			'maxlength' => '',
    //     		),
    //     		array(
    //     			'key' => 'subscription_date',
    //     			'label' => 'Subscription Date',
    //     			'name' => 'subscription_date',
    //     			'type' => 'text',
    //     			'instructions' => '',
    //     			'required' => 0,
    //     			'conditional_logic' => 0,
    //     			'wrapper' => array(
    //     				'width' => '',
    //     				'class' => '',
    //     				'id' => '',
    //     			),
    //     			'default_value' => '',
    //     			'placeholder' => '',
    //     			'prepend' => '',
    //     			'append' => '',
    //     			'maxlength' => '',
    //     		),
    //     	),
    //     	'location' => array(
    //     		array(
    //     			array(
    //     				'param' => 'post_type',
    //     				'operator' => '==',
    //     				'value' => 'member',
    //     			),
    //     		),
    //     	),
    //     	'menu_order' => 0,
    //     	'position' => 'normal',
    //     	'style' => 'default',
    //     	'label_placement' => 'top',
    //     	'instruction_placement' => 'label',
    //     	'hide_on_screen' => '',
    //     	'active' => 1,
    //     	'description' => '',
    //     ));
        
    //     acf_add_local_field_group(array(
    //     	'key' => 'group_5b74c600e98a7',
    //     	'title' => 'Member Health',
    //     	'fields' => array(
    //     		array(
    //     			'key' => 'field_5b74c6189699b',
    //     			'label' => 'ocupation',
    //     			'name' => 'ocupation',
    //     			'type' => 'text',
    //     			'instructions' => '',
    //     			'required' => 0,
    //     			'conditional_logic' => 0,
    //     			'wrapper' => array(
    //     				'width' => '',
    //     				'class' => '',
    //     				'id' => '',
    //     			),
    //     			'default_value' => '',
    //     			'placeholder' => '',
    //     			'prepend' => '',
    //     			'append' => '',
    //     			'maxlength' => '',
    //     		),
    //     		array(
    //     			'key' => 'field_5b74c6e49699c',
    //     			'label' => 'high cholesterol',
    //     			'name' => 'high_cholesterol',
    //     			'type' => 'text',
    //     			'instructions' => '',
    //     			'required' => 0,
    //     			'conditional_logic' => 0,
    //     			'wrapper' => array(
    //     				'width' => '',
    //     				'class' => '',
    //     				'id' => '',
    //     			),
    //     			'default_value' => '',
    //     			'placeholder' => '',
    //     			'prepend' => '',
    //     			'append' => '',
    //     			'maxlength' => '',
    //     		),
    //     		array(
    //     			'key' => 'field_5b74c7019699d',
    //     			'label' => 'obese',
    //     			'name' => 'obese',
    //     			'type' => 'text',
    //     			'instructions' => '',
    //     			'required' => 0,
    //     			'conditional_logic' => 0,
    //     			'wrapper' => array(
    //     				'width' => '',
    //     				'class' => '',
    //     				'id' => '',
    //     			),
    //     			'default_value' => '',
    //     			'placeholder' => '',
    //     			'prepend' => '',
    //     			'append' => '',
    //     			'maxlength' => '',
    //     		),
    //     		array(
    //     			'key' => 'field_5b74c7a29699e',
    //     			'label' => 'diabetes',
    //     			'name' => 'diabetes',
    //     			'type' => 'text',
    //     			'instructions' => '',
    //     			'required' => 0,
    //     			'conditional_logic' => 0,
    //     			'wrapper' => array(
    //     				'width' => '',
    //     				'class' => '',
    //     				'id' => '',
    //     			),
    //     			'default_value' => '',
    //     			'placeholder' => '',
    //     			'prepend' => '',
    //     			'append' => '',
    //     			'maxlength' => '',
    //     		),
    //     		array(
    //     			'key' => 'field_5b74c7b19699f',
    //     			'label' => 'hypertension',
    //     			'name' => 'hypertension',
    //     			'type' => 'text',
    //     			'instructions' => '',
    //     			'required' => 0,
    //     			'conditional_logic' => 0,
    //     			'wrapper' => array(
    //     				'width' => '',
    //     				'class' => '',
    //     				'id' => '',
    //     			),
    //     			'default_value' => '',
    //     			'placeholder' => '',
    //     			'prepend' => '',
    //     			'append' => '',
    //     			'maxlength' => '',
    //     		),
    //     		array(
    //     			'key' => 'field_5b74c7c0969a0',
    //     			'label' => 'heart attack',
    //     			'name' => 'heart_attack',
    //     			'type' => 'text',
    //     			'instructions' => '',
    //     			'required' => 0,
    //     			'conditional_logic' => 0,
    //     			'wrapper' => array(
    //     				'width' => '',
    //     				'class' => '',
    //     				'id' => '',
    //     			),
    //     			'default_value' => '',
    //     			'placeholder' => '',
    //     			'prepend' => '',
    //     			'append' => '',
    //     			'maxlength' => '',
    //     		),
    //     		array(
    //     			'key' => 'field_5b74c7d9969a1',
    //     			'label' => 'other cardiac diseases',
    //     			'name' => 'other_cardiac_diseases',
    //     			'type' => 'text',
    //     			'instructions' => '',
    //     			'required' => 0,
    //     			'conditional_logic' => 0,
    //     			'wrapper' => array(
    //     				'width' => '',
    //     				'class' => '',
    //     				'id' => '',
    //     			),
    //     			'default_value' => '',
    //     			'placeholder' => '',
    //     			'prepend' => '',
    //     			'append' => '',
    //     			'maxlength' => '',
    //     		),
    //     		array(
    //     			'key' => 'field_5b74c7f5969a2',
    //     			'label' => 'family cholesterol',
    //     			'name' => 'family_cholesterol',
    //     			'type' => 'text',
    //     			'instructions' => '',
    //     			'required' => 0,
    //     			'conditional_logic' => 0,
    //     			'wrapper' => array(
    //     				'width' => '',
    //     				'class' => '',
    //     				'id' => '',
    //     			),
    //     			'default_value' => '',
    //     			'placeholder' => '',
    //     			'prepend' => '',
    //     			'append' => '',
    //     			'maxlength' => '',
    //     		),
    //     		array(
    //     			'key' => 'field_5b74c841969a3',
    //     			'label' => 'family obese',
    //     			'name' => 'family_obese',
    //     			'type' => 'text',
    //     			'instructions' => '',
    //     			'required' => 0,
    //     			'conditional_logic' => 0,
    //     			'wrapper' => array(
    //     				'width' => '',
    //     				'class' => '',
    //     				'id' => '',
    //     			),
    //     			'default_value' => '',
    //     			'placeholder' => '',
    //     			'prepend' => '',
    //     			'append' => '',
    //     			'maxlength' => '',
    //     		),
    //     		array(
    //     			'key' => 'field_5b74c85d969a4',
    //     			'label' => 'family diabetes',
    //     			'name' => 'family_diabetes',
    //     			'type' => 'text',
    //     			'instructions' => '',
    //     			'required' => 0,
    //     			'conditional_logic' => 0,
    //     			'wrapper' => array(
    //     				'width' => '',
    //     				'class' => '',
    //     				'id' => '',
    //     			),
    //     			'default_value' => '',
    //     			'placeholder' => '',
    //     			'prepend' => '',
    //     			'append' => '',
    //     			'maxlength' => '',
    //     		),
    //     		array(
    //     			'key' => 'field_5b74c879969a5',
    //     			'label' => 'family hypertension',
    //     			'name' => 'family_hypertension',
    //     			'type' => 'text',
    //     			'instructions' => '',
    //     			'required' => 0,
    //     			'conditional_logic' => 0,
    //     			'wrapper' => array(
    //     				'width' => '',
    //     				'class' => '',
    //     				'id' => '',
    //     			),
    //     			'default_value' => '',
    //     			'placeholder' => '',
    //     			'prepend' => '',
    //     			'append' => '',
    //     			'maxlength' => '',
    //     		),
    //     		array(
    //     			'key' => 'field_5b74c890969a6',
    //     			'label' => 'family heart attack',
    //     			'name' => 'family_heart_attack',
    //     			'type' => 'text',
    //     			'instructions' => '',
    //     			'required' => 0,
    //     			'conditional_logic' => 0,
    //     			'wrapper' => array(
    //     				'width' => '',
    //     				'class' => '',
    //     				'id' => '',
    //     			),
    //     			'default_value' => '',
    //     			'placeholder' => '',
    //     			'prepend' => '',
    //     			'append' => '',
    //     			'maxlength' => '',
    //     		),
    //     		array(
    //     			'key' => 'field_5b74c8ad969a7',
    //     			'label' => 'other disease',
    //     			'name' => 'other_disease',
    //     			'type' => 'text',
    //     			'instructions' => '',
    //     			'required' => 0,
    //     			'conditional_logic' => 0,
    //     			'wrapper' => array(
    //     				'width' => '',
    //     				'class' => '',
    //     				'id' => '',
    //     			),
    //     			'default_value' => '',
    //     			'placeholder' => '',
    //     			'prepend' => '',
    //     			'append' => '',
    //     			'maxlength' => '',
    //     		),
    //     	),
    //     	'location' => array(
    //     		array(
    //     			array(
    //     				'param' => 'post_type',
    //     				'operator' => '==',
    //     				'value' => 'member',
    //     			),
    //     		),
    //     	),
    //     	'menu_order' => 0,
    //     	'position' => 'normal',
    //     	'style' => 'default',
    //     	'label_placement' => 'top',
    //     	'instruction_placement' => 'label',
    //     	'hide_on_screen' => '',
    //     	'active' => 1,
    //     	'description' => '',
    //     ));
        
    //     acf_add_local_field_group(array(
    //     	'key' => 'group_5b761fe90abb5',
    //     	'title' => 'Member Physical',
    //     	'fields' => array(
    //     		array(
    //     			'key' => 'field_5b762026d6120',
    //     			'label' => 'Fracture',
    //     			'name' => 'fracture',
    //     			'type' => 'text',
    //     			'instructions' => '',
    //     			'required' => 0,
    //     			'conditional_logic' => 0,
    //     			'wrapper' => array(
    //     				'width' => '',
    //     				'class' => '',
    //     				'id' => '',
    //     			),
    //     			'default_value' => '',
    //     			'placeholder' => '',
    //     			'prepend' => '',
    //     			'append' => '',
    //     			'maxlength' => '',
    //     		),
    //     		array(
    //     			'key' => 'field_5b762158d6121',
    //     			'label' => 'Luxation',
    //     			'name' => 'luxation',
    //     			'type' => 'text',
    //     			'instructions' => '',
    //     			'required' => 0,
    //     			'conditional_logic' => 0,
    //     			'wrapper' => array(
    //     				'width' => '',
    //     				'class' => '',
    //     				'id' => '',
    //     			),
    //     			'default_value' => '',
    //     			'placeholder' => '',
    //     			'prepend' => '',
    //     			'append' => '',
    //     			'maxlength' => '',
    //     		),
    //     		array(
    //     			'key' => 'field_5b7621add6122',
    //     			'label' => 'Sprain',
    //     			'name' => 'sprain',
    //     			'type' => 'text',
    //     			'instructions' => '',
    //     			'required' => 0,
    //     			'conditional_logic' => 0,
    //     			'wrapper' => array(
    //     				'width' => '',
    //     				'class' => '',
    //     				'id' => '',
    //     			),
    //     			'default_value' => '',
    //     			'placeholder' => '',
    //     			'prepend' => '',
    //     			'append' => '',
    //     			'maxlength' => '',
    //     		),
    //     		array(
    //     			'key' => 'field_5b7621e4d6123',
    //     			'label' => 'Column Injury',
    //     			'name' => 'column_injury',
    //     			'type' => 'text',
    //     			'instructions' => '',
    //     			'required' => 0,
    //     			'conditional_logic' => 0,
    //     			'wrapper' => array(
    //     				'width' => '',
    //     				'class' => '',
    //     				'id' => '',
    //     			),
    //     			'default_value' => '',
    //     			'placeholder' => '',
    //     			'prepend' => '',
    //     			'append' => '',
    //     			'maxlength' => '',
    //     		),
    //     		array(
    //     			'key' => 'field_5b7622b6d6124',
    //     			'label' => 'Lower Back Injury',
    //     			'name' => 'lower_back_injury',
    //     			'type' => 'text',
    //     			'instructions' => '',
    //     			'required' => 0,
    //     			'conditional_logic' => 0,
    //     			'wrapper' => array(
    //     				'width' => '',
    //     				'class' => '',
    //     				'id' => '',
    //     			),
    //     			'default_value' => '',
    //     			'placeholder' => '',
    //     			'prepend' => '',
    //     			'append' => '',
    //     			'maxlength' => '',
    //     		),
    //     		array(
    //     			'key' => 'field_5b762475d6125',
    //     			'label' => 'Knee Injury',
    //     			'name' => 'knee_injury',
    //     			'type' => 'text',
    //     			'instructions' => '',
    //     			'required' => 0,
    //     			'conditional_logic' => 0,
    //     			'wrapper' => array(
    //     				'width' => '',
    //     				'class' => '',
    //     				'id' => '',
    //     			),
    //     			'default_value' => '',
    //     			'placeholder' => '',
    //     			'prepend' => '',
    //     			'append' => '',
    //     			'maxlength' => '',
    //     		),
    //     		array(
    //     			'key' => 'field_5b762501d6126',
    //     			'label' => 'Repetitive Tear',
    //     			'name' => 'repetitive_tear',
    //     			'type' => 'text',
    //     			'instructions' => '',
    //     			'required' => 0,
    //     			'conditional_logic' => 0,
    //     			'wrapper' => array(
    //     				'width' => '',
    //     				'class' => '',
    //     				'id' => '',
    //     			),
    //     			'default_value' => '',
    //     			'placeholder' => '',
    //     			'prepend' => '',
    //     			'append' => '',
    //     			'maxlength' => '',
    //     		),
    //     		array(
    //     			'key' => 'field_5b762521d6127',
    //     			'label' => 'Chronic Pain',
    //     			'name' => 'chronic_pain',
    //     			'type' => 'text',
    //     			'instructions' => '',
    //     			'required' => 0,
    //     			'conditional_logic' => 0,
    //     			'wrapper' => array(
    //     				'width' => '',
    //     				'class' => '',
    //     				'id' => '',
    //     			),
    //     			'default_value' => '',
    //     			'placeholder' => '',
    //     			'prepend' => '',
    //     			'append' => '',
    //     			'maxlength' => '',
    //     		),
    //     		array(
    //     			'key' => 'field_5b762546d6128',
    //     			'label' => 'Physical Active',
    //     			'name' => 'physical_active',
    //     			'type' => 'text',
    //     			'instructions' => '',
    //     			'required' => 0,
    //     			'conditional_logic' => 0,
    //     			'wrapper' => array(
    //     				'width' => '',
    //     				'class' => '',
    //     				'id' => '',
    //     			),
    //     			'default_value' => '',
    //     			'placeholder' => '',
    //     			'prepend' => '',
    //     			'append' => '',
    //     			'maxlength' => '',
    //     		),
    //     		array(
    //     			'key' => 'field_5b762585d6129',
    //     			'label' => 'Examples of activities',
    //     			'name' => 'examples_of_activities',
    //     			'type' => 'text',
    //     			'instructions' => '',
    //     			'required' => 0,
    //     			'conditional_logic' => 0,
    //     			'wrapper' => array(
    //     				'width' => '',
    //     				'class' => '',
    //     				'id' => '',
    //     			),
    //     			'default_value' => '',
    //     			'placeholder' => '',
    //     			'prepend' => '',
    //     			'append' => '',
    //     			'maxlength' => '',
    //     		),
    //     		array(
    //     			'key' => 'field_5b7625a4d612a',
    //     			'label' => 'How many times a week',
    //     			'name' => 'how_many_times_a_week',
    //     			'type' => 'text',
    //     			'instructions' => '',
    //     			'required' => 0,
    //     			'conditional_logic' => 0,
    //     			'wrapper' => array(
    //     				'width' => '',
    //     				'class' => '',
    //     				'id' => '',
    //     			),
    //     			'default_value' => '',
    //     			'placeholder' => '',
    //     			'prepend' => '',
    //     			'append' => '',
    //     			'maxlength' => '',
    //     		),
    //     		array(
    //     			'key' => 'field_5b7625ded612b',
    //     			'label' => 'Purpose of the training',
    //     			'name' => 'purpose_of_the_training',
    //     			'type' => 'text',
    //     			'instructions' => '',
    //     			'required' => 0,
    //     			'conditional_logic' => 0,
    //     			'wrapper' => array(
    //     				'width' => '',
    //     				'class' => '',
    //     				'id' => '',
    //     			),
    //     			'default_value' => '',
    //     			'placeholder' => '',
    //     			'prepend' => '',
    //     			'append' => '',
    //     			'maxlength' => '',
    //     		),
    //     	),
    //     	'location' => array(
    //     		array(
    //     			array(
    //     				'param' => 'post_type',
    //     				'operator' => '==',
    //     				'value' => 'member',
    //     			),
    //     		),
    //     	),
    //     	'menu_order' => 0,
    //     	'position' => 'normal',
    //     	'style' => 'default',
    //     	'label_placement' => 'top',
    //     	'instruction_placement' => 'label',
    //     	'hide_on_screen' => '',
    //     	'active' => 1,
    //     	'description' => '',
    //     ));
        
    //     acf_add_local_field_group(array(
    //     	'key' => 'group_5b7628c1974c1',
    //     	'title' => 'Customer Goal',
    //     	'fields' => array(
    //     		array(
    //     			'key' => 'field_5b7628cf02461',
    //     			'label' => 'Whats your goal',
    //     			'name' => 'whats_your_goal',
    //     			'type' => 'text',
    //     			'instructions' => '',
    //     			'required' => 0,
    //     			'conditional_logic' => 0,
    //     			'wrapper' => array(
    //     				'width' => '',
    //     				'class' => '',
    //     				'id' => '',
    //     			),
    //     			'default_value' => '',
    //     			'placeholder' => '',
    //     			'prepend' => '',
    //     			'append' => '',
    //     			'maxlength' => '',
    //     		),
    //     	),
    //     	'location' => array(
    //     		array(
    //     			array(
    //     				'param' => 'post_type',
    //     				'operator' => '==',
    //     				'value' => 'member',
    //     			),
    //     		),
    //     	),
    //     	'menu_order' => 0,
    //     	'position' => 'normal',
    //     	'style' => 'default',
    //     	'label_placement' => 'top',
    //     	'instruction_placement' => 'label',
    //     	'hide_on_screen' => '',
    //     	'active' => 1,
    //     	'description' => '',
    //     ));
    
        acf_add_local_field_group(array(
        'key' => 'group_5b74b50bcbd29',
        'title' => 'Work Weekly Plan',
        'fields' => array(
        	array(
        		'key' => 'field_5b776bac32368',
        		'label' => 'Monday',
        		'name' => 'monday',
        		'type' => 'relationship',
        		'instructions' => '',
        		'required' => 0,
        		'conditional_logic' => 0,
        		'wrapper' => array(
        			'width' => '',
        			'class' => '',
        			'id' => '',
        		),
        		'post_type' => array(
        		),
        		'taxonomy' => array(
        		),
        		'filters' => array(
        			0 => 'post_type',
        		),
        		'elements' => '',
        		'min' => '',
        		'max' => '',
        		'return_format' => 'object',
        	),
        ),
        'location' => array(
        	array(
        		array(
        			'param' => 'post_type',
        			'operator' => '==',
        			'value' => 'member',
        		),
        	),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
        ));
        
    }

}

?>